# Generated by Django 4.2.7 on 2024-01-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0003_donationregister_memoryof_kn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='createdby',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
